spring.application.name=inventario
# ==== H2 DATABASE ====
spring.datasource.url=jdbc:sqlserver://Sachi-pc:1433;databaseName=papeleriapepe;trustServerCertificate=true;

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=eliza
spring.datasource.password=12345

# ==== JPA / HIBERNATE ====
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# ==== H2 CONSOLE ====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
